#!/bin/zsh
echo "Updating homebrew"
brew update
echo "Upgrading formulae"
brew upgrade
echo "Upgrading outdated casks"
brew outdated --cask --greedy --verbose | grep -v '(latest)' | awk '{print $1}' | xargs brew reinstall --cask
